name: Upload og:image

on:
  push:
    branches:
      - main
    paths:
      - 'articles/**'

env:
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: 'npm'
          node-version: 24

      - name: Install modules
        run: npm ci

      - name: Generate og:image files
        run: npm run gen:ogimage

      - name: Sync og:image folder to S3
        run: |
          aws s3 sync dist/og_images s3://${{ env.AWS_BUCKET_NAME }}/images/og --delete --exact-timestamps
